#!/bin/zsh
echo $(
  docker ps -a --format "table {{.ID}}\t{{.Names}}\t{{.Image}}" | tail -n +2 |\
    fzf --ansi --no-sort --tiebreak=index --bind=ctrl-s:toggle-sort --query=$1 \
  ) | head -n1 | awk '{print $1;}'
